import { Inter } from 'next/font/google'
import Navigation from '../components/Navigation.jsx'
import 'bootstrap/dist/css/bootstrap.css'


import '../styles/globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Arvo&family=Lora&display=swap" rel="stylesheet"/>
        <likn rel='icon' href='/icon.png'/>
      </Head>

      <body className={inter.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
